In [1]:
import numpy as np

In [2]:
X_train = np.array([[1, 1],
                    [1, 0],
                    [0, 1],
                    [2, 1]])

Y_train = np.array([1, 2, 1, -1])

lambda_ridge = 1

def squared_exponential_kernel(x, x_prime):
    return np.exp(-0.5 * np.linalg.norm(x - x_prime)**2)

n_samples = X_train.shape[0]
K = np.zeros((n_samples, n_samples))

for i in range(n_samples):
    for j in range(n_samples):
        K[i, j] = squared_exponential_kernel(X_train[i], X_train[j])

In [3]:
print(K)

[[1.         0.60653066 0.60653066 0.60653066]
 [0.60653066 1.         0.36787944 0.36787944]
 [0.60653066 0.36787944 1.         0.13533528]
 [0.60653066 0.36787944 0.13533528 1.        ]]


In [4]:
I = np.eye(n_samples)
alpha = np.linalg.inv(K + lambda_ridge * I) @ Y_train

In [5]:
print(alpha)

[ 0.36634729  0.98992087  0.26168507 -0.81089381]


In [6]:
x_new = np.array([0, 0])
k_new = np.array([squared_exponential_kernel(x_new, X_train[i]) for i in range(n_samples)])

y_new_pred = k_new.T @ alpha

In [8]:
print(k_new)

[0.36787944 0.60653066 0.60653066 0.082085  ]


In [7]:
print(y_new_pred)

0.8273467967630496
